/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:RuleAst
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_PARSERGEN_RULEAST_AST_TRAVERSE_VISITOR
#define VCZH_PARSER2_PARSERGEN_RULEAST_AST_TRAVERSE_VISITOR

#include "ParserGenRuleAst.h"

namespace vl
{
	namespace glr
	{
		namespace parsergen
		{
			namespace traverse_visitor
			{
				/// <summary>A traverse visitor, overriding all abstract methods with AST visiting code.</summary>
				class RuleAstVisitor
					: public vl::Object
					, protected virtual GlrSyntax::IVisitor
					, protected virtual GlrClause::IVisitor
				{
				protected:
					virtual void Traverse(vl::glr::ParsingToken& token);
					virtual void Traverse(vl::glr::ParsingAstBase* node);
					virtual void Traverse(GlrAssignment* node);
					virtual void Traverse(GlrClause* node);
					virtual void Traverse(GlrCreateClause* node);
					virtual void Traverse(GlrLiteralSyntax* node);
					virtual void Traverse(GlrLoopSyntax* node);
					virtual void Traverse(GlrOptionalSyntax* node);
					virtual void Traverse(GlrPartialClause* node);
					virtual void Traverse(GlrRefSyntax* node);
					virtual void Traverse(GlrRule* node);
					virtual void Traverse(GlrSequenceSyntax* node);
					virtual void Traverse(GlrSyntax* node);
					virtual void Traverse(GlrSyntaxFile* node);
					virtual void Traverse(GlrUseSyntax* node);
					virtual void Traverse(Glr_ReuseClause* node);

				protected:
					virtual void Finishing(vl::glr::ParsingAstBase* node);
					virtual void Finishing(GlrAssignment* node);
					virtual void Finishing(GlrClause* node);
					virtual void Finishing(GlrCreateClause* node);
					virtual void Finishing(GlrLiteralSyntax* node);
					virtual void Finishing(GlrLoopSyntax* node);
					virtual void Finishing(GlrOptionalSyntax* node);
					virtual void Finishing(GlrPartialClause* node);
					virtual void Finishing(GlrRefSyntax* node);
					virtual void Finishing(GlrRule* node);
					virtual void Finishing(GlrSequenceSyntax* node);
					virtual void Finishing(GlrSyntax* node);
					virtual void Finishing(GlrSyntaxFile* node);
					virtual void Finishing(GlrUseSyntax* node);
					virtual void Finishing(Glr_ReuseClause* node);

				protected:
					void Visit(GlrRefSyntax* node) override;
					void Visit(GlrLiteralSyntax* node) override;
					void Visit(GlrUseSyntax* node) override;
					void Visit(GlrLoopSyntax* node) override;
					void Visit(GlrOptionalSyntax* node) override;
					void Visit(GlrSequenceSyntax* node) override;

					void Visit(GlrCreateClause* node) override;
					void Visit(GlrPartialClause* node) override;
					void Visit(Glr_ReuseClause* node) override;

				public:
					void InspectInto(GlrSyntax* node);
					void InspectInto(GlrClause* node);
					void InspectInto(GlrAssignment* node);
					void InspectInto(GlrRule* node);
					void InspectInto(GlrSyntaxFile* node);
				};
			}
		}
	}
}
#endif