/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:ParserGen
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_PARSERGEN_AST_ASSEMBLER
#define VCZH_PARSER2_PARSERGEN_AST_ASSEMBLER

#include "ParserGenRuleAst.h"
#include "ParserGenTypeAst.h"

namespace vl
{
	namespace glr
	{
		namespace parsergen
		{
			enum class ParserGenClasses : vl::vint32_t
			{
				AlternativeSyntax = 0,
				AndCondition = 1,
				Assignment = 2,
				AstFile = 3,
				Class = 4,
				ClassProp = 5,
				Clause = 6,
				Condition = 7,
				CreateClause = 8,
				Enum = 9,
				EnumItem = 10,
				LeftRecursionInjectClause = 11,
				LeftRecursionInjectContinuation = 12,
				LeftRecursionPlaceholder = 13,
				LeftRecursionPlaceholderClause = 14,
				LoopSyntax = 15,
				NotCondition = 16,
				OptionalSyntax = 17,
				OrCondition = 18,
				PartialClause = 19,
				PrefixMergeClause = 20,
				PushConditionSyntax = 21,
				RefCondition = 22,
				RefSyntax = 23,
				ReuseClause = 24,
				Rule = 25,
				SequenceSyntax = 26,
				SwitchItem = 27,
				Syntax = 28,
				SyntaxFile = 29,
				TestConditionBranch = 30,
				TestConditionSyntax = 31,
				Type = 32,
				UseSyntax = 33,
			};

			enum class ParserGenFields : vl::vint32_t
			{
				AlternativeSyntax_first = 0,
				AlternativeSyntax_second = 1,
				AndCondition_first = 2,
				AndCondition_second = 3,
				Assignment_field = 4,
				Assignment_type = 5,
				Assignment_value = 6,
				AstFile_types = 7,
				Class_ambiguity = 8,
				Class_baseClass = 9,
				Class_props = 10,
				ClassProp_name = 11,
				ClassProp_propType = 12,
				ClassProp_propTypeName = 13,
				CreateClause_assignments = 14,
				CreateClause_syntax = 15,
				CreateClause_type = 16,
				Enum_items = 17,
				EnumItem_name = 18,
				LeftRecursionInjectClause_continuation = 19,
				LeftRecursionInjectClause_rule = 20,
				LeftRecursionInjectClause_switches = 21,
				LeftRecursionInjectContinuation_configuration = 22,
				LeftRecursionInjectContinuation_flag = 23,
				LeftRecursionInjectContinuation_injectionTargets = 24,
				LeftRecursionInjectContinuation_type = 25,
				LeftRecursionPlaceholder_flag = 26,
				LeftRecursionPlaceholderClause_flags = 27,
				LoopSyntax_delimiter = 28,
				LoopSyntax_syntax = 29,
				NotCondition_condition = 30,
				OptionalSyntax_priority = 31,
				OptionalSyntax_syntax = 32,
				OrCondition_first = 33,
				OrCondition_second = 34,
				PartialClause_assignments = 35,
				PartialClause_syntax = 36,
				PartialClause_type = 37,
				PrefixMergeClause_rule = 38,
				PushConditionSyntax_switches = 39,
				PushConditionSyntax_syntax = 40,
				RefCondition_name = 41,
				RefSyntax_field = 42,
				RefSyntax_literal = 43,
				RefSyntax_refType = 44,
				ReuseClause_assignments = 45,
				ReuseClause_syntax = 46,
				Rule_clauses = 47,
				Rule_name = 48,
				Rule_type = 49,
				SequenceSyntax_first = 50,
				SequenceSyntax_second = 51,
				SwitchItem_name = 52,
				SwitchItem_value = 53,
				SyntaxFile_rules = 54,
				SyntaxFile_switches = 55,
				TestConditionBranch_condition = 56,
				TestConditionBranch_syntax = 57,
				TestConditionSyntax_branches = 58,
				Type_name = 59,
				UseSyntax_name = 60,
			};

			extern const wchar_t* ParserGenTypeName(ParserGenClasses type);
			extern const wchar_t* ParserGenCppTypeName(ParserGenClasses type);
			extern const wchar_t* ParserGenFieldName(ParserGenFields field);
			extern const wchar_t* ParserGenCppFieldName(ParserGenFields field);

			class ParserGenAstInsReceiver : public vl::glr::AstInsReceiverBase
			{
			protected:
				vl::Ptr<vl::glr::ParsingAstBase> CreateAstNode(vl::vint32_t type) override;
				void SetField(vl::glr::ParsingAstBase* object, vl::vint32_t field, vl::Ptr<vl::glr::ParsingAstBase> value) override;
				void SetField(vl::glr::ParsingAstBase* object, vl::vint32_t field, const vl::regex::RegexToken& token, vl::vint32_t tokenIndex) override;
				void SetField(vl::glr::ParsingAstBase* object, vl::vint32_t field, vl::vint32_t enumItem, bool weakAssignment) override;
				vl::Ptr<vl::glr::ParsingAstBase> ResolveAmbiguity(vl::vint32_t type, vl::collections::Array<vl::Ptr<vl::glr::ParsingAstBase>>& candidates) override;
			};
		}
	}
}
#endif