/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:TypeAst
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#include "ParserGenTypeAst_Builder.h"

namespace vl
{
	namespace glr
	{
		namespace parsergen
		{
			namespace builder
			{

/***********************************************************************
ClassBuilder
***********************************************************************/

				ClassBuilder& ClassBuilder::props(const vl::Ptr<GlrClassProp>& value)
				{
					node->props.Add(value);
					return *this;
				}

/***********************************************************************
ClassPropBuilder
***********************************************************************/

				ClassPropBuilder& ClassPropBuilder::name(const vl::WString& value)
				{
					node->name.value = value;
					return *this;
				}

				ClassPropBuilder& ClassPropBuilder::propType(GlrPropType value)
				{
					node->propType = value;
					return *this;
				}

				ClassPropBuilder& ClassPropBuilder::propTypeName(const vl::WString& value)
				{
					node->propTypeName.value = value;
					return *this;
				}

/***********************************************************************
EnumBuilder
***********************************************************************/

				EnumBuilder& EnumBuilder::items(const vl::Ptr<GlrEnumItem>& value)
				{
					node->items.Add(value);
					return *this;
				}

/***********************************************************************
EnumItemBuilder
***********************************************************************/

				EnumItemBuilder& EnumItemBuilder::name(const vl::WString& value)
				{
					node->name.value = value;
					return *this;
				}

/***********************************************************************
FileBuilder
***********************************************************************/

				FileBuilder& FileBuilder::name(const vl::WString& value)
				{
					node->name.value = value;
					return *this;
				}

				FileBuilder& FileBuilder::types(const vl::Ptr<GlrType>& value)
				{
					node->types.Add(value);
					return *this;
				}

/***********************************************************************
TypeBuilder
***********************************************************************/

				TypeBuilder& TypeBuilder::name(const vl::WString& value)
				{
					node->name.value = value;
					return *this;
				}
			}
		}
	}
}
