/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:ParserGen
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_PARSERGEN_LEXER
#define VCZH_PARSER2_PARSERGEN_LEXER

#include "../AstBase.h"
#include "../SyntaxBase.h"

namespace vl
{
	namespace glr
	{
		namespace parsergen
		{
			enum class ParserGenTokens : vl::vint32_t
			{
				CLASS = 0,
				ENUM = 1,
				VAR = 2,
				TOKEN = 3,
				AS = 4,
				PARTIAL = 5,
				OPEN_ROUND = 6,
				CLOSE_ROUND = 7,
				OPEN_SQUARE = 8,
				CLOSE_SQUARE = 9,
				OPEN_CURLY = 10,
				CLOSE_CURLY = 11,
				COMMA = 12,
				COLON = 13,
				SEMICOLON = 14,
				INFER = 15,
				USE = 16,
				ASSIGN = 17,
				ID = 18,
				STRING = 19,
				SPACE = 20,
			};

			constexpr vl::vint ParserGenTokenCount = 21;
			extern bool ParserGenTokenDeleter(vl::vint token);
			extern const wchar_t* ParserGenTokenId(ParserGenTokens token);
			extern const wchar_t* ParserGenTokenDisplayText(ParserGenTokens token);
			extern const wchar_t* ParserGenTokenRegex(ParserGenTokens token);
			extern void ParserGenLexerData(vl::stream::IStream& outputStream);
		}
	}
}
#endif