/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:RuleAst
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_PARSERGEN_RULEAST_AST_JSON_VISITOR
#define VCZH_PARSER2_PARSERGEN_RULEAST_AST_JSON_VISITOR

#include "ParserGenRuleAst.h"

namespace vl
{
	namespace glr
	{
		namespace parsergen
		{
			namespace json_visitor
			{
				/// <summary>A JSON visitor, overriding all abstract methods with AST to JSON serialization code.</summary>
				class RuleAstVisitor
					: public vl::glr::JsonVisitorBase
					, protected virtual GlrClause::IVisitor
				{
				protected:
					virtual void PrintFields(GlrAssignment* node);
					virtual void PrintFields(GlrClause* node);
					virtual void PrintFields(GlrCreateClause* node);
					virtual void PrintFields(GlrLiteralClause* node);
					virtual void PrintFields(GlrLoopClause* node);
					virtual void PrintFields(GlrOptionalClause* node);
					virtual void PrintFields(GlrRefClause* node);
					virtual void PrintFields(GlrRule* node);
					virtual void PrintFields(GlrSequenceClause* node);
					virtual void PrintFields(GlrSyntaxFile* node);
					virtual void PrintFields(GlrUseClause* node);
					virtual void PrintFields(Glr_ReuseClause* node);

				protected:
					void Visit(GlrRefClause* node) override;
					void Visit(GlrLiteralClause* node) override;
					void Visit(GlrUseClause* node) override;
					void Visit(GlrLoopClause* node) override;
					void Visit(GlrOptionalClause* node) override;
					void Visit(GlrSequenceClause* node) override;
					void Visit(GlrCreateClause* node) override;
					void Visit(Glr_ReuseClause* node) override;

				public:
					RuleAstVisitor(vl::stream::StreamWriter& _writer);

					void Print(GlrClause* node);
					void Print(GlrAssignment* node);
					void Print(GlrRule* node);
					void Print(GlrSyntaxFile* node);
				};
			}
		}
	}
}
#endif