/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:RuleAst
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_PARSERGEN_RULEAST_AST_COPY_VISITOR
#define VCZH_PARSER2_PARSERGEN_RULEAST_AST_COPY_VISITOR

#include "ParserGenRuleAst.h"

namespace vl
{
	namespace glr
	{
		namespace parsergen
		{
			namespace copy_visitor
			{
				/// <summary>A copy visitor, overriding all abstract methods with AST copying code.</summary>
				class RuleAstVisitor
					: public virtual vl::glr::CopyVisitorBase
					, protected virtual GlrSyntax::IVisitor
					, protected virtual GlrClause::IVisitor
				{
				protected:
					void CopyFields(GlrAlternativeSyntax* from, GlrAlternativeSyntax* to);
					void CopyFields(GlrAssignment* from, GlrAssignment* to);
					void CopyFields(GlrClause* from, GlrClause* to);
					void CopyFields(GlrCreateClause* from, GlrCreateClause* to);
					void CopyFields(GlrLiteralSyntax* from, GlrLiteralSyntax* to);
					void CopyFields(GlrLoopSyntax* from, GlrLoopSyntax* to);
					void CopyFields(GlrOptionalSyntax* from, GlrOptionalSyntax* to);
					void CopyFields(GlrPartialClause* from, GlrPartialClause* to);
					void CopyFields(GlrRefSyntax* from, GlrRefSyntax* to);
					void CopyFields(GlrReuseClause* from, GlrReuseClause* to);
					void CopyFields(GlrRule* from, GlrRule* to);
					void CopyFields(GlrSequenceSyntax* from, GlrSequenceSyntax* to);
					void CopyFields(GlrSyntax* from, GlrSyntax* to);
					void CopyFields(GlrSyntaxFile* from, GlrSyntaxFile* to);
					void CopyFields(GlrUseSyntax* from, GlrUseSyntax* to);

				protected:
					virtual void Visit(GlrAssignment* node);
					virtual void Visit(GlrRule* node);
					virtual void Visit(GlrSyntaxFile* node);

					void Visit(GlrRefSyntax* node) override;
					void Visit(GlrLiteralSyntax* node) override;
					void Visit(GlrUseSyntax* node) override;
					void Visit(GlrLoopSyntax* node) override;
					void Visit(GlrOptionalSyntax* node) override;
					void Visit(GlrSequenceSyntax* node) override;
					void Visit(GlrAlternativeSyntax* node) override;

					void Visit(GlrCreateClause* node) override;
					void Visit(GlrPartialClause* node) override;
					void Visit(GlrReuseClause* node) override;

				public:
					virtual vl::Ptr<GlrSyntax> CopyNode(GlrSyntax* node);
					virtual vl::Ptr<GlrClause> CopyNode(GlrClause* node);
					virtual vl::Ptr<GlrAssignment> CopyNode(GlrAssignment* node);
					virtual vl::Ptr<GlrRule> CopyNode(GlrRule* node);
					virtual vl::Ptr<GlrSyntaxFile> CopyNode(GlrSyntaxFile* node);

					vl::Ptr<GlrAlternativeSyntax> CopyNode(GlrAlternativeSyntax* node);
					vl::Ptr<GlrCreateClause> CopyNode(GlrCreateClause* node);
					vl::Ptr<GlrLiteralSyntax> CopyNode(GlrLiteralSyntax* node);
					vl::Ptr<GlrLoopSyntax> CopyNode(GlrLoopSyntax* node);
					vl::Ptr<GlrOptionalSyntax> CopyNode(GlrOptionalSyntax* node);
					vl::Ptr<GlrPartialClause> CopyNode(GlrPartialClause* node);
					vl::Ptr<GlrRefSyntax> CopyNode(GlrRefSyntax* node);
					vl::Ptr<GlrReuseClause> CopyNode(GlrReuseClause* node);
					vl::Ptr<GlrSequenceSyntax> CopyNode(GlrSequenceSyntax* node);
					vl::Ptr<GlrUseSyntax> CopyNode(GlrUseSyntax* node);
				};
			}
		}
	}
}
#endif