/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:ParserGen
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_PARSERGEN_LEXER
#define VCZH_PARSER2_PARSERGEN_LEXER

#include "../AstBase.h"
#include "../SyntaxBase.h"

namespace vl
{
	namespace glr
	{
		namespace parsergen
		{
			enum class ParserGenTokens : vl::vint32_t
			{
				AMBIGUOUS = 0,
				CLASS = 1,
				ENUM = 2,
				VAR = 3,
				TOKEN = 4,
				AS = 5,
				PARTIAL = 6,
				OPEN_ROUND = 7,
				CLOSE_ROUND = 8,
				OPEN_SQUARE = 9,
				CLOSE_SQUARE = 10,
				OPEN_CURLY = 11,
				CLOSE_CURLY = 12,
				COMMA = 13,
				COLON = 14,
				SEMICOLON = 15,
				INFER = 16,
				ALTERNATIVE = 17,
				USE = 18,
				ASSIGN = 19,
				POSITIVE = 20,
				NEGATIVE = 21,
				ID = 22,
				STRING = 23,
				SPACE = 24,
				COMMENT = 25,
			};

			constexpr vl::vint ParserGenTokenCount = 26;
			extern bool ParserGenTokenDeleter(vl::vint token);
			extern const wchar_t* ParserGenTokenId(ParserGenTokens token);
			extern const wchar_t* ParserGenTokenDisplayText(ParserGenTokens token);
			extern const wchar_t* ParserGenTokenRegex(ParserGenTokens token);
			extern void ParserGenLexerData(vl::stream::IStream& outputStream);
		}
	}
}
#endif