/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:TypeAst
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_PARSERGEN_TYPEAST_AST_JSON
#define VCZH_PARSER2_PARSERGEN_TYPEAST_AST_JSON

#include "ParserGenTypeAst.h"
#include "../Json/Generated/JsonAst.h"

namespace vl::glr::parsergen
{
	namespace json_visitor
	{
		/// <summary>A JSON visitor, overriding all abstract methods with AST to JSON serialization code.</summary>
		class TypeAstVisitor
			: public vl::glr::JsonVisitorBase
			, protected virtual GlrType::IVisitor
		{
		protected:
			virtual void PrintFields(GlrAstFile* node);
			virtual void PrintFields(GlrClass* node);
			virtual void PrintFields(GlrClassProp* node);
			virtual void PrintFields(GlrEnum* node);
			virtual void PrintFields(GlrEnumItem* node);
			virtual void PrintFields(GlrType* node);

		protected:
			void Visit(GlrEnum* node) override;
			void Visit(GlrClass* node) override;

		public:
			TypeAstVisitor(vl::stream::StreamWriter& _writer);

			void Print(GlrType* node);
			void Print(GlrEnumItem* node);
			void Print(GlrClassProp* node);
			void Print(GlrAstFile* node);
		};
	}

	namespace json_reader
	{
		/// <summary>A JSON reader, overriding all abstract methods with JSON to AST deserialization code.</summary>
		class TypeAstVisitor
			: protected virtual GlrType::IVisitor
		{
		protected:
			class JsonObjectScope
			{
			protected:
				vl::collections::List<vl::glr::json::JsonObject*>& jsonObjects;

			public:
				JsonObjectScope(vl::collections::List<vl::glr::json::JsonObject*>& _jsonObjects, vl::glr::json::JsonObject* json);
				~JsonObjectScope();
			};

			vl::collections::List<vl::glr::json::JsonObject*> jsonObjects;
			vl::glr::json::JsonObject* CurrentObject();
			vl::glr::json::JsonNode* FindField(const vl::WString& name);
			bool IsNull(vl::glr::json::JsonNode* value);
			vl::WString ReadType(vl::glr::json::JsonObject* json);
			void ValidateFields(vl::glr::json::JsonObject* json, const vl::WString& typeName);

			virtual void FillFields(GlrAstFile* node);
			virtual void FillFields(GlrClass* node);
			virtual void FillFields(GlrClassProp* node);
			virtual void FillFields(GlrEnum* node);
			virtual void FillFields(GlrEnumItem* node);
			virtual void FillFields(GlrType* node);

		protected:
			void Visit(GlrEnum* node) override;
			void Visit(GlrClass* node) override;

		public:
			vl::Ptr<vl::glr::ParsingAstBase> ReadJson(vl::glr::json::JsonObject* json);
		};
	}
}
#endif