/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:Calculator
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_UNITTEST_CALCULATOR_AST_TRAVERSEVISITOR
#define VCZH_PARSER2_UNITTEST_CALCULATOR_AST_TRAVERSEVISITOR

#include "CalculatorAst_Traverse.h"

namespace calculator
{
	namespace traverse_visitor
	{
	}
}
#endif