/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:Ast
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_UNITTEST_CALCULATORAST_AST_JSONVISITOR
#define VCZH_PARSER2_UNITTEST_CALCULATORAST_AST_JSONVISITOR

#include "../../../Source/AstBase.h"
#include "CalculatorAst.h"

namespace calculator
{
	namespace json_visitor
	{
		/// <summary>A JSON visitor, overriding all abstract methods with AST to JSON serialization code.</summary>
		class AstVisitor
			: public vl::glr::JsonVisitorBase
			, protected virtual Expr::IVisitor
			, protected virtual Expandable::IVisitor
		{
		protected:
			virtual void PrintFields(Arg* from, Arg* to);
			virtual void PrintFields(Binary* from, Binary* to);
			virtual void PrintFields(Call* from, Call* to);
			virtual void PrintFields(Expandable* from, Expandable* to);
			virtual void PrintFields(Expr* from, Expr* to);
			virtual void PrintFields(False* from, False* to);
			virtual void PrintFields(Func* from, Func* to);
			virtual void PrintFields(Import* from, Import* to);
			virtual void PrintFields(LetExpr* from, LetExpr* to);
			virtual void PrintFields(Module* from, Module* to);
			virtual void PrintFields(NumExpr* from, NumExpr* to);
			virtual void PrintFields(Ref* from, Ref* to);
			virtual void PrintFields(True* from, True* to);
			virtual void PrintFields(Unary* from, Unary* to);

		protected:
			void Visit(NumExpr* node) override;
			void Visit(Ref* node) override;
			void Visit(True* node) override;
			void Visit(False* node) override;
			void Visit(Func* node) override;
			void Visit(Call* node) override;
			void Visit(Expandable* node) override;

			void Visit(LetExpr* node) override;
			void Visit(Unary* node) override;
			void Visit(Binary* node) override;

		public:
			AstVisitor(vl::stream::StreamWriter& _writer);

			void Print(Expr* node);
			void Print(Arg* node);
			void Print(Import* node);
			void Print(Module* node);
		};
	}
}
#endif