/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:Calculator
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_UNITTEST_CALCULATOR_AST_COPYVISITOR
#define VCZH_PARSER2_UNITTEST_CALCULATOR_AST_COPYVISITOR

#include "CalculatorAst_Copy"

namespace calculator
{
	namespace copy_visitor
	{
		/// <summary>A copy visitor, overriding all abstract methods with AST copying code.</summary>
		class CalculatorRootVisitor
			: public virtual vl::glr::CopyVisitorBase
			: public virtual calculator::Expandable::IVisitor
			: public virtual calculator::Expr::IVisitor
		{
		};

	}
}
#endif