/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:Ast
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#include "../../../Source/AstBase.h"
#include "CalculatorAst_Empty.h"

namespace calculator
{
	namespace empty_visitor
	{

/***********************************************************************
ExprVisitor
***********************************************************************/

		// Visitor Members -----------------------------------

		void ExprVisitor::Visit(NumExpr* node)
		{
		}

		void ExprVisitor::Visit(Ref* node)
		{
		}

		void ExprVisitor::Visit(True* node)
		{
		}

		void ExprVisitor::Visit(False* node)
		{
		}

		void ExprVisitor::Visit(Func* node)
		{
		}

		void ExprVisitor::Visit(Call* node)
		{
		}

		void ExprVisitor::Visit(Expandable* node)
		{
			Dispatch(node);
		}

/***********************************************************************
ExpandableVisitor
***********************************************************************/

		// Visitor Members -----------------------------------

		void ExpandableVisitor::Visit(LetExpr* node)
		{
		}

		void ExpandableVisitor::Visit(Unary* node)
		{
		}

		void ExpandableVisitor::Visit(Binary* node)
		{
		}
	}
}
