/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:Calculator
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_UNITTEST_CALCULATOR_AST_ASSEMBLER
#define VCZH_PARSER2_UNITTEST_CALCULATOR_AST_ASSEMBLER

#include "CalculatorAst.h"

namespace calculator
{
}
#endif