/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:CalculatorAst
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#include "../../../Source/AstBase.h"
#include "CalculatorAst_Copy.h"

namespace calculator
{
	namespace copy_visitor
	{

/***********************************************************************
ExprVisitor
***********************************************************************/

		// CopyFields ----------------------------------------

		void ExprVisitor::CopyFields(Expr* from, Expr* to)
		{
		}

		void ExprVisitor::CopyFields(NumExpr* from, NumExpr* to)
		{
			CopyFields(static_cast<Expr*>(from), static_cast<Expr*>(to));
			to->value = from->value;
		}

		void ExprVisitor::CopyFields(Ref* from, Ref* to)
		{
			CopyFields(static_cast<Expr*>(from), static_cast<Expr*>(to));
			to->name = from->name;
		}

		void ExprVisitor::CopyFields(True* from, True* to)
		{
			CopyFields(static_cast<Expr*>(from), static_cast<Expr*>(to));
		}

		void ExprVisitor::CopyFields(False* from, False* to)
		{
			CopyFields(static_cast<Expr*>(from), static_cast<Expr*>(to));
		}

		void ExprVisitor::CopyFields(Func* from, Func* to)
		{
			CopyFields(static_cast<Expr*>(from), static_cast<Expr*>(to));
			for (auto listItem : from->args)
			{
				to->args.Add(CreateField(listItem));
			}
			to->value = CreateField(from->value);
		}

		void ExprVisitor::CopyFields(Arg* from, Arg* to)
		{
			to->name = from->name;
		}

		void ExprVisitor::CopyFields(Call* from, Call* to)
		{
			CopyFields(static_cast<Expr*>(from), static_cast<Expr*>(to));
			to->arg = CreateField(from->arg);
			to->func = CreateField(from->func);
		}

		// CreateField ---------------------------------------

		vl::Ptr<Arg> ExprVisitor::CreateField(vl::Ptr<Arg> from)
		{
			if (!from) return nullptr;
			auto to = vl::MakePtr<Arg>();
			CopyFields(from.Obj(), to.Obj());
			return to;
		}

		// Visitor Members -----------------------------------

		void ExprVisitor::Visit(NumExpr* node)
		{
			auto newNode = vl::MakePtr<NumExpr>();
			CopyFields(node, newNode.Obj());
			this->result = newNode;
		}

		void ExprVisitor::Visit(Ref* node)
		{
			auto newNode = vl::MakePtr<Ref>();
			CopyFields(node, newNode.Obj());
			this->result = newNode;
		}

		void ExprVisitor::Visit(True* node)
		{
			auto newNode = vl::MakePtr<True>();
			CopyFields(node, newNode.Obj());
			this->result = newNode;
		}

		void ExprVisitor::Visit(False* node)
		{
			auto newNode = vl::MakePtr<False>();
			CopyFields(node, newNode.Obj());
			this->result = newNode;
		}

		void ExprVisitor::Visit(Func* node)
		{
			auto newNode = vl::MakePtr<Func>();
			CopyFields(node, newNode.Obj());
			this->result = newNode;
		}

		void ExprVisitor::Visit(Call* node)
		{
			auto newNode = vl::MakePtr<Call>();
			CopyFields(node, newNode.Obj());
			this->result = newNode;
		}

		void ExprVisitor::Visit(Expandable* node)
		{
			Dispatch(node);
		}

/***********************************************************************
ExpandableVisitor
***********************************************************************/

		// CopyFields ----------------------------------------

		void ExpandableVisitor::CopyFields(Expr* from, Expr* to)
		{
		}

		void ExpandableVisitor::CopyFields(Expandable* from, Expandable* to)
		{
			CopyFields(static_cast<Expr*>(from), static_cast<Expr*>(to));
			to->expanded = CreateField(from->expanded);
		}

		void ExpandableVisitor::CopyFields(LetExpr* from, LetExpr* to)
		{
			CopyFields(static_cast<Expandable*>(from), static_cast<Expandable*>(to));
			to->name = from->name;
			to->value = CreateField(from->value);
		}

		void ExpandableVisitor::CopyFields(Unary* from, Unary* to)
		{
			CopyFields(static_cast<Expandable*>(from), static_cast<Expandable*>(to));
			to->op = from->op;
			to->operand = CreateField(from->operand);
		}

		void ExpandableVisitor::CopyFields(Binary* from, Binary* to)
		{
			CopyFields(static_cast<Expandable*>(from), static_cast<Expandable*>(to));
			to->left = CreateField(from->left);
			to->op = from->op;
			to->right = CreateField(from->right);
		}

		// CreateField ---------------------------------------

		// Visitor Members -----------------------------------

		void ExpandableVisitor::Visit(LetExpr* node)
		{
			auto newNode = vl::MakePtr<LetExpr>();
			CopyFields(node, newNode.Obj());
			this->result = newNode;
		}

		void ExpandableVisitor::Visit(Unary* node)
		{
			auto newNode = vl::MakePtr<Unary>();
			CopyFields(node, newNode.Obj());
			this->result = newNode;
		}

		void ExpandableVisitor::Visit(Binary* node)
		{
			auto newNode = vl::MakePtr<Binary>();
			CopyFields(node, newNode.Obj());
			this->result = newNode;
		}
	}
}
