/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:Ast
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#include "../../../Source/AstBase.h"
#include "CalculatorAst_Traverse.h"

namespace calculator
{
	namespace traverse_visitor
	{

/***********************************************************************
ExprVisitor
***********************************************************************/

		// Traverse ------------------------------------------

		void ExprVisitor::Traverse(vl::glr::ParsingToken& token)
		{
		}

		void ExprVisitor::Traverse(vl::glr::ParsingAstBase* node)
		{
		}

		void ExprVisitor::Traverse(Expr* node)
		{
		}

		void ExprVisitor::Traverse(NumExpr* node)
		{
		}

		void ExprVisitor::Traverse(Ref* node)
		{
		}

		void ExprVisitor::Traverse(True* node)
		{
		}

		void ExprVisitor::Traverse(False* node)
		{
		}

		void ExprVisitor::Traverse(Func* node)
		{
		}

		void ExprVisitor::Traverse(Arg* node)
		{
		}

		void ExprVisitor::Traverse(Call* node)
		{
		}

		// Finishing -----------------------------------------

		void ExprVisitor::Finishing(vl::glr::ParsingAstBase* node)
		{
		}

		void ExprVisitor::Finishing(Expr* node)
		{
		}

		void ExprVisitor::Finishing(NumExpr* node)
		{
		}

		void ExprVisitor::Finishing(Ref* node)
		{
		}

		void ExprVisitor::Finishing(True* node)
		{
		}

		void ExprVisitor::Finishing(False* node)
		{
		}

		void ExprVisitor::Finishing(Func* node)
		{
		}

		void ExprVisitor::Finishing(Arg* node)
		{
		}

		void ExprVisitor::Finishing(Call* node)
		{
		}

		// VisitField ----------------------------------------

		void ExprVisitor::VisitField(Arg* node)
		{
			if (!node) return;
			Traverse(static_cast<Arg*>(node));
			Traverse(static_cast<vl::glr::ParsingAstBase*>(node));
			Traverse(node->name);
			Finishing(static_cast<vl::glr::ParsingAstBase*>(node));
			Finishing(static_cast<Arg*>(node));
		}

		// Visitor Members -----------------------------------

		void ExprVisitor::Visit(NumExpr* node)
		{
			if (!node) return;
			Traverse(static_cast<NumExpr*>(node));
			Traverse(static_cast<Expr*>(node));
			Traverse(static_cast<vl::glr::ParsingAstBase*>(node));
			Traverse(node->value);
			Finishing(static_cast<vl::glr::ParsingAstBase*>(node));
			Finishing(static_cast<Expr*>(node));
			Finishing(static_cast<NumExpr*>(node));
		}

		void ExprVisitor::Visit(Ref* node)
		{
			if (!node) return;
			Traverse(static_cast<Ref*>(node));
			Traverse(static_cast<Expr*>(node));
			Traverse(static_cast<vl::glr::ParsingAstBase*>(node));
			Traverse(node->name);
			Finishing(static_cast<vl::glr::ParsingAstBase*>(node));
			Finishing(static_cast<Expr*>(node));
			Finishing(static_cast<Ref*>(node));
		}

		void ExprVisitor::Visit(True* node)
		{
			if (!node) return;
			Traverse(static_cast<True*>(node));
			Traverse(static_cast<Expr*>(node));
			Traverse(static_cast<vl::glr::ParsingAstBase*>(node));
			Finishing(static_cast<vl::glr::ParsingAstBase*>(node));
			Finishing(static_cast<Expr*>(node));
			Finishing(static_cast<True*>(node));
		}

		void ExprVisitor::Visit(False* node)
		{
			if (!node) return;
			Traverse(static_cast<False*>(node));
			Traverse(static_cast<Expr*>(node));
			Traverse(static_cast<vl::glr::ParsingAstBase*>(node));
			Finishing(static_cast<vl::glr::ParsingAstBase*>(node));
			Finishing(static_cast<Expr*>(node));
			Finishing(static_cast<False*>(node));
		}

		void ExprVisitor::Visit(Func* node)
		{
			if (!node) return;
			Traverse(static_cast<Func*>(node));
			Traverse(static_cast<Expr*>(node));
			Traverse(static_cast<vl::glr::ParsingAstBase*>(node));
			for (auto&& listItem : node->args)
			{
				Traverse(listItem.Obj());
			}
			Traverse(node->value.Obj());
			Finishing(static_cast<vl::glr::ParsingAstBase*>(node));
			Finishing(static_cast<Expr*>(node));
			Finishing(static_cast<Func*>(node));
		}

		void ExprVisitor::Visit(Call* node)
		{
			if (!node) return;
			Traverse(static_cast<Call*>(node));
			Traverse(static_cast<Expr*>(node));
			Traverse(static_cast<vl::glr::ParsingAstBase*>(node));
			Traverse(node->arg.Obj());
			Traverse(node->func.Obj());
			Finishing(static_cast<vl::glr::ParsingAstBase*>(node));
			Finishing(static_cast<Expr*>(node));
			Finishing(static_cast<Call*>(node));
		}

		void ExprVisitor::Visit(Expandable* node)
		{
			Dispatch(node);
		}

/***********************************************************************
ExpandableVisitor
***********************************************************************/

		// Traverse ------------------------------------------

		void ExpandableVisitor::Traverse(vl::glr::ParsingToken& token)
		{
		}

		void ExpandableVisitor::Traverse(vl::glr::ParsingAstBase* node)
		{
		}

		void ExpandableVisitor::Traverse(Expr* node)
		{
		}

		void ExpandableVisitor::Traverse(Expandable* node)
		{
		}

		void ExpandableVisitor::Traverse(LetExpr* node)
		{
		}

		void ExpandableVisitor::Traverse(Unary* node)
		{
		}

		void ExpandableVisitor::Traverse(Binary* node)
		{
		}

		// Finishing -----------------------------------------

		void ExpandableVisitor::Finishing(vl::glr::ParsingAstBase* node)
		{
		}

		void ExpandableVisitor::Finishing(Expr* node)
		{
		}

		void ExpandableVisitor::Finishing(Expandable* node)
		{
		}

		void ExpandableVisitor::Finishing(LetExpr* node)
		{
		}

		void ExpandableVisitor::Finishing(Unary* node)
		{
		}

		void ExpandableVisitor::Finishing(Binary* node)
		{
		}

		// VisitField ----------------------------------------

		// Visitor Members -----------------------------------

		void ExpandableVisitor::Visit(LetExpr* node)
		{
			if (!node) return;
			Traverse(static_cast<LetExpr*>(node));
			Traverse(static_cast<Expandable*>(node));
			Traverse(static_cast<Expr*>(node));
			Traverse(static_cast<vl::glr::ParsingAstBase*>(node));
			Traverse(node->name);
			Traverse(node->value.Obj());
			Finishing(static_cast<vl::glr::ParsingAstBase*>(node));
			Finishing(static_cast<Expr*>(node));
			Finishing(static_cast<Expandable*>(node));
			Finishing(static_cast<LetExpr*>(node));
		}

		void ExpandableVisitor::Visit(Unary* node)
		{
			if (!node) return;
			Traverse(static_cast<Unary*>(node));
			Traverse(static_cast<Expandable*>(node));
			Traverse(static_cast<Expr*>(node));
			Traverse(static_cast<vl::glr::ParsingAstBase*>(node));
			Traverse(node->operand.Obj());
			Finishing(static_cast<vl::glr::ParsingAstBase*>(node));
			Finishing(static_cast<Expr*>(node));
			Finishing(static_cast<Expandable*>(node));
			Finishing(static_cast<Unary*>(node));
		}

		void ExpandableVisitor::Visit(Binary* node)
		{
			if (!node) return;
			Traverse(static_cast<Binary*>(node));
			Traverse(static_cast<Expandable*>(node));
			Traverse(static_cast<Expr*>(node));
			Traverse(static_cast<vl::glr::ParsingAstBase*>(node));
			Traverse(node->left.Obj());
			Traverse(node->right.Obj());
			Finishing(static_cast<vl::glr::ParsingAstBase*>(node));
			Finishing(static_cast<Expr*>(node));
			Finishing(static_cast<Expandable*>(node));
			Finishing(static_cast<Binary*>(node));
		}
	}
}
