/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:CalculatorAst
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_UNITTEST_CALCULATOR_AST
#define VCZH_PARSER2_UNITTEST_CALCULATOR_AST

#include "../../../Source/AstBase.h"

namespace calculator
{
}
namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION

#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA

#endif
#endif
			/// <summary>Load all reflectable AST types, only available when <b>VCZH_DEBUG_NO_REFLECTION</b> is off.</summary>
			/// <returns>Returns true if this operation succeeded.</returns>
			extern bool CalculatorAstLoadTypes();
		}
	}
}
#endif