/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:ParserGen
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_PARSERGEN_AST_COPYVISITOR
#define VCZH_PARSER2_PARSERGEN_AST_COPYVISITOR

#include "ParserGenTypeAst_Copy"

namespace vl
{
	namespace glr
	{
		namespace parsergen
		{
			namespace copy_visitor
			{
				/// <summary>A copy visitor, overriding all abstract methods with AST copying code.</summary>
				class ParserGenRootVisitor
					: public virtual vl::glr::CopyVisitorBase
					: public virtual vl::glr::parsergen::GlrType::IVisitor
				{
				};

			}
		}
	}
}
#endif