/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:TypeAst
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#include "../AstBase.h"
#include "ParserGenTypeAst_Copy.h"

namespace vl
{
	namespace glr
	{
		namespace parsergen
		{
			namespace copy_visitor
			{

/***********************************************************************
TypeVisitor
***********************************************************************/

				// CopyFields ----------------------------------------

				void TypeVisitor::CopyFields(GlrType* from, GlrType* to)
				{
					to->name = from->name;
				}

				void TypeVisitor::CopyFields(GlrEnum* from, GlrEnum* to)
				{
					CopyFields(static_cast<GlrType*>(from), static_cast<GlrType*>(to));
					for (auto listItem : from->items)
					{
						to->items.Add(CreateField(listItem));
					}
				}

				void TypeVisitor::CopyFields(GlrEnumItem* from, GlrEnumItem* to)
				{
					to->name = from->name;
				}

				void TypeVisitor::CopyFields(GlrClass* from, GlrClass* to)
				{
					CopyFields(static_cast<GlrType*>(from), static_cast<GlrType*>(to));
					for (auto listItem : from->props)
					{
						to->props.Add(CreateField(listItem));
					}
				}

				void TypeVisitor::CopyFields(GlrClassProp* from, GlrClassProp* to)
				{
					to->name = from->name;
					to->propType = from->propType;
					to->propTypeName = from->propTypeName;
				}

				// CreateField ---------------------------------------

				vl::Ptr<GlrEnumItem> TypeVisitor::CreateField(vl::Ptr<GlrEnumItem> from)
				{
					static_assert(false);
				}

				vl::Ptr<GlrClassProp> TypeVisitor::CreateField(vl::Ptr<GlrClassProp> from)
				{
					static_assert(false);
				}

				// Visitor Members -----------------------------------

				void TypeVisitor::Visit(GlrEnum* node)
				{
					static_assert(false);
				}

				void TypeVisitor::Visit(GlrClass* node)
				{
					static_assert(false);
				}
			}
		}
	}
}
