/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:ParserGen
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#include "ParserGen_RootCopy.h"

namespace vl
{
	namespace glr
	{
		namespace parsergen
		{
			namespace copy_visitor
			{

				// CopyFields ----------------------------------------

				void ParserGenRootCopyVisitor::CopyFields(vl::glr::parsergen::GlrClassProp* from, vl::glr::parsergen::GlrClassProp* to)
				{
					to->name = from->name;
					to->propType = from->propType;
					to->propTypeName = from->propTypeName;
				}

				void ParserGenRootCopyVisitor::CopyFields(vl::glr::parsergen::GlrEnumItem* from, vl::glr::parsergen::GlrEnumItem* to)
				{
					to->name = from->name;
				}

				void ParserGenRootCopyVisitor::CopyFields(vl::glr::parsergen::GlrFile* from, vl::glr::parsergen::GlrFile* to)
				{
					to->name = from->name;
					for (auto&& listItem : from->types)
					{
						to->types.Add(CreateField(listItem));
					}
				}

				// Dispatch (virtual) --------------------------------

				// CreateField ---------------------------------------

				vl::Ptr<vl::glr::parsergen::GlrClassProp> ParserGenRootCopyVisitor::CreateField(vl::Ptr<vl::glr::parsergen::GlrClassProp> from)
				{
					Visit(from.Obj());
					return this->result.Cast<vl::glr::parsergen::GlrClassProp>();
				}

				vl::Ptr<vl::glr::parsergen::GlrEnumItem> ParserGenRootCopyVisitor::CreateField(vl::Ptr<vl::glr::parsergen::GlrEnumItem> from)
				{
					Visit(from.Obj());
					return this->result.Cast<vl::glr::parsergen::GlrEnumItem>();
				}

				vl::Ptr<vl::glr::parsergen::GlrFile> ParserGenRootCopyVisitor::CreateField(vl::Ptr<vl::glr::parsergen::GlrFile> from)
				{
					Visit(from.Obj());
					return this->result.Cast<vl::glr::parsergen::GlrFile>();
				}

				vl::Ptr<vl::glr::parsergen::GlrType> ParserGenRootCopyVisitor::CreateField(vl::Ptr<vl::glr::parsergen::GlrType> from)
				{
					from->Accept(static_cast<vl::glr::parsergen::GlrType::IVisitor*>(this));
					return this->result.Cast<vl::glr::parsergen::GlrType>();
				}

				// Visitor Members -----------------------------------

				void ParserGenRootCopyVisitor::Visit(vl::glr::parsergen::GlrClassProp* node)
				{
					auto newNode = vl::MakePtr<vl::glr::parsergen::GlrClassProp>();
					CopyFields(node, newNode.Obj());
					this->result = newNode;
				}

				void ParserGenRootCopyVisitor::Visit(vl::glr::parsergen::GlrEnumItem* node)
				{
					auto newNode = vl::MakePtr<vl::glr::parsergen::GlrEnumItem>();
					CopyFields(node, newNode.Obj());
					this->result = newNode;
				}

				void ParserGenRootCopyVisitor::Visit(vl::glr::parsergen::GlrFile* node)
				{
					auto newNode = vl::MakePtr<vl::glr::parsergen::GlrFile>();
					CopyFields(node, newNode.Obj());
					this->result = newNode;
				}
			}
		}
	}
}
