/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:ParserGen
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_PARSERGEN_AST_ASSEMBLER
#define VCZH_PARSER2_PARSERGEN_AST_ASSEMBLER

#include "ParserGenTypeAst.h"

namespace vl
{
	namespace glr
	{
		namespace parsergen
		{
			enum class ParserGenClasses : vl::vint32_t
			{
				Class = 0,
				ClassProp = 1,
				Enum = 2,
				EnumItem = 3,
				File = 4,
				Type = 5,
			};

			enum class ParserGenFields : vl::vint32_t
			{
				Class_props = (static_cast<vl::vint32_t>(ParserGenClasses::Class) << 8) + 0,
				ClassProp_name = (static_cast<vl::vint32_t>(ParserGenClasses::ClassProp) << 8) + 0,
				ClassProp_propType = (static_cast<vl::vint32_t>(ParserGenClasses::ClassProp) << 8) + 1,
				ClassProp_propTypeName = (static_cast<vl::vint32_t>(ParserGenClasses::ClassProp) << 8) + 2,
				Enum_items = (static_cast<vl::vint32_t>(ParserGenClasses::Enum) << 8) + 0,
				EnumItem_name = (static_cast<vl::vint32_t>(ParserGenClasses::EnumItem) << 8) + 0,
				File_name = (static_cast<vl::vint32_t>(ParserGenClasses::File) << 8) + 0,
				File_types = (static_cast<vl::vint32_t>(ParserGenClasses::File) << 8) + 1,
				Type_name = (static_cast<vl::vint32_t>(ParserGenClasses::Type) << 8) + 0,
			};

			class ParserGenAstInsReceiver : public vl::glr::AstInsReceiverBase
			{
			protected:
				vl::Ptr<vl::glr::ParsingAstBase> CreateAstNode(vl::vint32_t type) override;
				void SetField(vl::glr::ParsingAstBase* object, vl::vint32_t field, vl::Ptr<vl::glr::ParsingAstBase> value) override;
				void SetField(vl::glr::ParsingAstBase* object, vl::vint32_t field, const vl::regex::RegexToken& token) override;
				void SetField(vl::glr::ParsingAstBase* object, vl::vint32_t field, vl::vint32_t enumItem) override;
				vl::Ptr<vl::glr::ParsingAstBase> ResolveAmbiguity(vl::vint32_t type, vl::collections::Array<vl::Ptr<vl::glr::ParsingAstBase>>& candidates) override;
			};
		}
	}
}
#endif