/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:TypeAst
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_PARSERGEN_EXPRESSION_AST
#define VCZH_PARSER2_PARSERGEN_EXPRESSION_AST

#include "../AstBase.h"

namespace vl
{
	namespace glr
	{
		namespace parsergen
		{
			class GlrClass;
			class GlrClassProp;
			class GlrEnum;
			class GlrEnumItem;
			class GlrFile;
			class GlrType;

			class GlrType abstract : public vl::glr::ParsingAstBase, vl::reflection::Description<GlrType>
			{
			public:
				class IVisitor : public vl::reflection::IDescriptable, vl::reflection::Description<IVisitor>
				{
				public:
					virtual void Visit(GlrEnum* node) = 0;
					virtual void Visit(GlrClass* node) = 0;
				};

				virtual void Accept(GlrType::IVisitor* visitor)=0;

				vl::glr::ParsingToken name;
			};

			class GlrEnumItem : public vl::glr::ParsingAstBase, vl::reflection::Description<GlrEnumItem>
			{
			public:
				vl::glr::ParsingToken name;
			};

			class GlrEnum : public GlrType, vl::reflection::Description<GlrEnum>
			{
			public:
				vl::collections::List<GlrEnumItem> items;

				void Accept(GlrType::IVisitor* visitor) override;
			};

			enum class GlrPropType
			{
				Token = 0,
				Type = 1,
				Array = 2,
			};

			class GlrClassProp : public vl::glr::ParsingAstBase, vl::reflection::Description<GlrClassProp>
			{
			public:
				vl::glr::ParsingToken name;
				GlrPropType propType;
				vl::glr::ParsingToken propTypeName;
			};

			class GlrClass : public GlrType, vl::reflection::Description<GlrClass>
			{
			public:
				vl::collections::List<GlrClassProp> props;

				void Accept(GlrType::IVisitor* visitor) override;
			};

			class GlrFile : public vl::glr::ParsingAstBase, vl::reflection::Description<GlrFile>
			{
			public:
				vl::glr::ParsingToken name;
				vl::collections::List<GlrType> types;
			};
		}
	}
}
namespace vl
{
	namespace reflection
	{
		namespace description
		{
		}
	}
}
#endif