/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:ParserGen
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_PARSERGEN_AST_TRAVERSEVISITOR
#define VCZH_PARSER2_PARSERGEN_AST_TRAVERSEVISITOR

#include "ParserGenTypeAst_Traverse.h"

namespace vl
{
	namespace glr
	{
		namespace parsergen
		{
			namespace traverse_visitor
			{
				/// <summary>A traverse visitor, overriding all abstract methods with AST visiting code.</summary>
				class ParserGenRootTraverseVisitor
					: public virtual vl::Object
					, public virtual vl::glr::parsergen::traverse_visitor::TypeVisitor
				{
				protected:
					// Traverse ------------------------------------------
					virtual void Traverse(vl::glr::ParsingToken& token) override;
					virtual void Traverse(vl::glr::ParsingAstBase* node) override;
					virtual void Traverse(vl::glr::parsergen::GlrType* node) override;
					virtual void Traverse(vl::glr::parsergen::GlrClassProp* node) override;
					virtual void Traverse(vl::glr::parsergen::GlrEnumItem* node) override;
					virtual void Traverse(vl::glr::parsergen::GlrFile* node);

					// Finishing -----------------------------------------
					virtual void Finishing(vl::glr::ParsingAstBase* node) override;
					virtual void Finishing(vl::glr::parsergen::GlrType* node) override;
					virtual void Finishing(vl::glr::parsergen::GlrClassProp* node) override;
					virtual void Finishing(vl::glr::parsergen::GlrEnumItem* node) override;
					virtual void Finishing(vl::glr::parsergen::GlrFile* node);

					// Dispatch (virtual) --------------------------------

				public:
					// VisitField ----------------------------------------
					void VisitField(vl::glr::parsergen::GlrClassProp* node) override;
					void VisitField(vl::glr::parsergen::GlrEnumItem* node) override;
					void VisitField(vl::glr::parsergen::GlrFile* node);
					void VisitField(vl::glr::parsergen::GlrType* node);
				};

			}
		}
	}
}
#endif