/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:ParserGen
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_PARSERGEN_AST_COPYVISITOR
#define VCZH_PARSER2_PARSERGEN_AST_COPYVISITOR

#include "ParserGenTypeAst_Copy"

namespace vl
{
	namespace glr
	{
		namespace parsergen
		{
			namespace copy_visitor
			{
				/// <summary>A copy visitor, overriding all abstract methods with AST copying code.</summary>
				class ParserGenRootVisitor
					: public virtual vl::glr::CopyVisitorBase
					: public virtual vl::glr::parsergen::GlrType::IVisitor
				{
				protected:
					// CopyFields ----------------------------------------
					void CopyFields(vl::glr::parsergen::GlrClassProp* from, vl::glr::parsergen::GlrClassProp* to);
					void CopyFields(vl::glr::parsergen::GlrEnumItem* from, vl::glr::parsergen::GlrEnumItem* to);
					void CopyFields(vl::glr::parsergen::GlrFile* from, vl::glr::parsergen::GlrFile* to);

					// Dispatch (virtual) --------------------------------

				public:
					// CreateField ---------------------------------------
					virtual vl::Ptr<vl::glr::parsergen::GlrClassProp> CreateField(vl::Ptr<vl::glr::parsergen::GlrClassProp> from) override;
					virtual vl::Ptr<vl::glr::parsergen::GlrEnumItem> CreateField(vl::Ptr<vl::glr::parsergen::GlrEnumItem> from) override;
					virtual vl::Ptr<vl::glr::parsergen::GlrFile> CreateField(vl::Ptr<vl::glr::parsergen::GlrFile> from);
					virtual vl::Ptr<vl::glr::parsergen::GlrType> CreateField(vl::Ptr<vl::glr::parsergen::GlrType> from);

					// Visitor Members -----------------------------------
					virtual void Visit(vl::glr::parsergen::GlrClassProp* node);
					virtual void Visit(vl::glr::parsergen::GlrEnumItem* node);
					virtual void Visit(vl::glr::parsergen::GlrFile* node);
				};

			}
		}
	}
}
#endif