/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:TypeAst
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#include "../AstBase.h"
#include "ParserGenTypeAst_Builder.h"

namespace vl
{
	namespace glr
	{
		namespace parsergen
		{
			namespace builder
			{

/***********************************************************************
ClassBuilder
***********************************************************************/

				ClassBuilder& ClassBuilder::props(vl::Ptr<GlrClassProp> value)
				{
					return *this;
				}

/***********************************************************************
ClassPropBuilder
***********************************************************************/

				ClassPropBuilder& ClassPropBuilder::name(const vl::WString& value)
				{
					return *this;
				}

				ClassPropBuilder& ClassPropBuilder::propType(GlrPropType value)
				{
					return *this;
				}

				ClassPropBuilder& ClassPropBuilder::propTypeName(const vl::WString& value)
				{
					return *this;
				}

/***********************************************************************
EnumBuilder
***********************************************************************/

				EnumBuilder& EnumBuilder::items(vl::Ptr<GlrEnumItem> value)
				{
					return *this;
				}

/***********************************************************************
EnumItemBuilder
***********************************************************************/

				EnumItemBuilder& EnumItemBuilder::name(const vl::WString& value)
				{
					return *this;
				}

/***********************************************************************
FileBuilder
***********************************************************************/

				FileBuilder& FileBuilder::name(const vl::WString& value)
				{
					return *this;
				}

				FileBuilder& FileBuilder::types(vl::Ptr<GlrType> value)
				{
					return *this;
				}

/***********************************************************************
TypeBuilder
***********************************************************************/

				TypeBuilder& TypeBuilder::name(const vl::WString& value)
				{
					return *this;
				}
			}
		}
	}
}
