/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:TypeAst
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_PARSERGEN_EXPRESSION_AST_TRAVERSEVISITOR
#define VCZH_PARSER2_PARSERGEN_EXPRESSION_AST_TRAVERSEVISITOR

#include "../AstBase.h"
#include "ParserGenTypeAst.h"

namespace vl
{
	namespace glr
	{
		namespace parsergen
		{
			namespace traverse_visitor
			{
			}
		}
	}
}
#endif