/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:Calculator
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_UNITTEST_CALCULATOR_MODULEPARSER_SYNTAX
#define VCZH_PARSER2_UNITTEST_CALCULATOR_MODULEPARSER_SYNTAX

#include "../../../../Source/AstBase.h"
#include "../../../../Source/SyntaxBase.h"

namespace calculator
{
}
#endif