/***********************************************************************
This file is generated by: Vczh Parser Generator
From parser definition:Calculator
Licensed under https://github.com/vczh-libraries/License
***********************************************************************/

#ifndef VCZH_PARSER2_UNITTEST_CALCULATOR_LEXER
#define VCZH_PARSER2_UNITTEST_CALCULATOR_LEXER

#include "../../../../Source/AstBase.h"

namespace calculator
{
	enum class CalculatorTokens : vl::vint32_t
	{
		ADD = 0,
		SUB = 1,
		MUL = 2,
		DIV = 3,
		GT = 4,
		GE = 5,
		LT = 6,
		LE = 7,
		EQ = 8,
		NE = 9,
		OPEN_BRACE = 10,
		CLOSE_BRACE = 11,
		COMMA = 12,
		INFER = 13,
		ASSIGN = 14,
		TRUE = 15,
		FALSE = 16,
		LET = 17,
		IN = 18,
		IMPORT = 19,
		EXPORT = 20,
		NUM = 21,
		ID = 22,
		SPACE = 23,
	};

	extern bool			CalculatorTokenDeleter(vl::vint token);
	extern void*		CalculatorLexerData(void);
	extern vl::vint		CalculatorLexerDataSize(void);
}
#endif